import numpy as np
import json
from typing import List, Union
from rag_eval_utils import get_embedding


def cosine_similarity(s1, s2):
    embeddings = get_embedding([s1, s2])
    assert len(embeddings) == 2
    embedding_1, embedding_2 = embeddings[0], embeddings[1]
    dot_product = np.dot(embedding_1, embedding_2)
    
    norm_1 = np.linalg.norm(embedding_1)
    norm_2 = np.linalg.norm(embedding_2)
    
    if norm_1 == 0 or norm_2 == 0:
        return 0.0
    else:
        return dot_product / (norm_1 * norm_2)


def answer_similarity(answers: List[str], ground_truth: List[str]):
    """
    Answer Semantic Similarity refers to measuring how closely the meaning of a generated answer matches the ground truth.
    This evaluation yields a score between 0 and 1, where higher scores indicate a stronger alignment with the ground truth.
    This result is computed based on question/answer/ground_truth
    
    Required Args:
    answer: the answer generated by llm
    ground_truth: the ground_truth answer
    """
    assert len(ground_truth) == len(answers)
    res = []
    for g,a in zip(ground_truth, answers):
        score = cosine_similarity(g, a)
        res.append(score)
    return res    
        
    
if __name__ == "__main__":
    
    questions = [
        "who was the first superbowl held?", 
           "Who are the main characters in Reunion under the Stars story", 
           "What is the main story line for Reunion under the stars story",
           "What is the revenue reported for quarter ending and year ending for Alphabet?"
           ]
    answers = [
        "the first superbowl was held on 01/15/1967",
        "The main characters in the story 'Reunion Under The Stars' are Aarav and Priya. Aarav is a scientist who moved to the United States, and Priya is a famous artist. They are childhood friends from India who reunite after many years.",
        """The main storyline of "Reunion Under The Stars" revolves around two friends, Aarav and Priya, who reunite in the United States after many years apart. Aarav, now a scientist, and Priya, a famous artist, both originally from India, meet in a park filled with the cheerful chatter of children and the sweet melody of birds singing. Their reunion is filled with joy and excitement as they share stories of their adventures, dreams, and memories of their childhood in India. They spend the day together, exploring the city, enjoying Indian food, and reminiscing about the festivals and monsoon rains they miss. Aarav shows Priya his lab, and Priya shares her artwork with Aarav, showcasing their pride in each other's achievements. As the day turns into evening, they sit on a park bench under the stars and make a promise to never let distance or time diminish their friendship. They plan to meet more often and keep the essence of their homeland alive in their hearts, no matter where life takes them. Their reunion under the starlit sky reminds them of the unbreakable bond they share, proving that true friendship knows no boundaries."""
        ,"""For the quarter and year ending December 31, 2023, Alphabet reported the following revenues:- **Quarter Ended December 31, 2023:**- Revenue: $86.31 billion- **Year Ended December 31, 2023:**- Revenue: $307.39 billion"""
    ]
    ground_truths = [
        "The first superbowl was held on Jan 15, 1967", 
           """The main characters in "Reunion Under the Stars" are Aarav and Priya. Aarav is a scientist who moved to the United States, and Priya is a famous artist. They both hail from India and share a deep, enduring friendship that remains strong despite the distance and time apart.""",
    """The main storyline of "Reunion Under the Stars" revolves around the heartwarming reunion of two childhood friends, Aarav and Priya, who both hail from India. Aarav has moved to the United States to become a scientist, while Priya has become a famous artist. Despite the years and distance that have separated them, their friendship remains strong.The story begins with Aarav and Priya meeting again in a bustling city park in the U.S. They share a joyful and emotional reunion, reminiscing about their childhood in India and catching up on each other's lives. They explore the city together, enjoying Indian food and sharing stories about their respective journeys and achievements.As the day turns into evening, they sit under the stars and make a promise to maintain their friendship despite the distance. They vow to meet more often and keep the essence of their homeland alive in their hearts. The story highlights the enduring bond of friendship that transcends time and distance, celebrating the magic of their enduring connection.""",
           """For the quarter ending December 31, 2023, Alphabet Inc. reported consolidated revenues of $86.31 billion, up 13% year over year. For the fiscal year ending on the same date, the company's consolidated revenues were reported as $307.394 billion, which is a 9% increase compared to the previous year"""
           ]
    res = answer_similarity( answers, ground_truths)
    print(res)