import numpy as np
import json
from typing import List, Union
from rag_eval_utils import llm_call


CORRECTNESS_INSTRUCTIONS = """
Given a ground truth and an answer, find factual statement in each of them and classify each factual statement in one of the following categories:

- TP (true positive): statement present in the answer and statement in the ground truth that share the same/equivalent semantic meaning.
- FP (false positive): statement found in the answer but can't not entail from any statements in the ground truth.
- FN (false negative): statement found in the ground truth but but can't not entail from any statements in the answer.

Each statement can and must only belong to one of the 3 categories above. Again, if a statement in answer and a statement in ground truth has same meaning but just presented in different way, it should be categorized as TP.

Please generate your output in json format, with 3 field `TP`, `FP`, and `FN`. The value of each of them should be a list of statements that are categorized as that type.
If a statement in answer and a statement in ground truth share the same semantic meaning (so it's TP), only include 1 of them in the output you return.
Do not include '```json'.

GIVEN GROUND TRUTH:
{groundtruth}

ANSWER:
{answer}
"""


## To me, This is the most important metric on the Answer generation side. 
# Ideally, LLM should generate answer with as much details as possible but without hallucination.

def answer_factuality(answers: List[str], ground_truths: List[str]):
    """
    NOTE: This is more like a `F1-score` version of model's answer_factuality, as it takes TP/FP/FN into consideration.
    According to this paper: https://arxiv.org/pdf/2307.16877, using the `recall` version, aka TP/(TP+FN), proportion of tokens in the reference answer that are also in the model's response, is a good choice.

    Required Args:
    question: the origin question
    answer: the answer generated by llm
    ground_truth: the ground truth answer
    """
    assert len(ground_truths) == len(answers)
    res = []
    for g,a in zip(ground_truths, answers):
        
        s = llm_call(CORRECTNESS_INSTRUCTIONS.format(groundtruth=g, answer=a))
        try:
            loaded_s = json.loads(s)
            tp, fp, fn = len(loaded_s["TP"]), len(loaded_s["FP"]), len(loaded_s["FN"])
            f1_score = tp / (tp + 0.5 * (fp + fn)) if tp != 0 else 0
            res.append(f1_score)
        except Exception as e:
            print(e)
        
    return res    
        
    
if __name__ == "__main__":
    
    answers = [
        "the first superbowl was held on 01/15/1967",
        "The main characters in the story 'Reunion Under The Stars' are Aarav and Priya. Aarav is a scientist who moved to the United States, and Priya is a famous artist. They are childhood friends from India who reunite after many years.",
        """The main storyline of "Reunion Under The Stars" revolves around two friends, Aarav and Priya, who reunite in the United States after many years apart. Aarav, now a scientist, and Priya, a famous artist, both originally from India, meet in a park filled with the cheerful chatter of children and the sweet melody of birds singing. Their reunion is filled with joy and excitement as they share stories of their adventures, dreams, and memories of their childhood in India. They spend the day together, exploring the city, enjoying Indian food, and reminiscing about the festivals and monsoon rains they miss. Aarav shows Priya his lab, and Priya shares her artwork with Aarav, showcasing their pride in each other's achievements. As the day turns into evening, they sit on a park bench under the stars and make a promise to never let distance or time diminish their friendship. They plan to meet more often and keep the essence of their homeland alive in their hearts, no matter where life takes them. Their reunion under the starlit sky reminds them of the unbreakable bond they share, proving that true friendship knows no boundaries."""
        ,"""For the quarter and year ending December 31, 2023, Alphabet reported the following revenues:- **Quarter Ended December 31, 2023:**- Revenue: $86.31 billion- **Year Ended December 31, 2023:**- Revenue: $307.39 billion"""
    ]
    ground_truths = [
        "The first superbowl was held on Jan 15, 1967", 
           """The main characters in "Reunion Under the Stars" are Aarav and Priya. Aarav is a scientist who moved to the United States, and Priya is a famous artist. They both hail from India and share a deep, enduring friendship that remains strong despite the distance and time apart.""",
    """The main storyline of "Reunion Under the Stars" revolves around the heartwarming reunion of two childhood friends, Aarav and Priya, who both hail from India. Aarav has moved to the United States to become a scientist, while Priya has become a famous artist. Despite the years and distance that have separated them, their friendship remains strong.The story begins with Aarav and Priya meeting again in a bustling city park in the U.S. They share a joyful and emotional reunion, reminiscing about their childhood in India and catching up on each other's lives. They explore the city together, enjoying Indian food and sharing stories about their respective journeys and achievements.As the day turns into evening, they sit under the stars and make a promise to maintain their friendship despite the distance. They vow to meet more often and keep the essence of their homeland alive in their hearts. The story highlights the enduring bond of friendship that transcends time and distance, celebrating the magic of their enduring connection.""",
           """For the quarter ending December 31, 2023, Alphabet Inc. reported consolidated revenues of $86.31 billion, up 13% year over year. For the fiscal year ending on the same date, the company's consolidated revenues were reported as $307.394 billion, which is a 9% increase compared to the previous year"""
           ]
    res = answer_factuality( answers, ground_truths)